services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "/app/prueba.py"]

volumes:
  pg_data:
